import type { Toilet } from "./types";

/**
 * ⚠️ 임시 하드코딩 데이터입니다. 실제 화장실 정보가 아닙니다.
 *
 * 공공데이터포털 점검(~2026-08-02)으로 API 키를 받을 수 없어, 지도·마커·상세를
 * 먼저 만들기 위해 인하대 주변 좌표로 만든 개발용 표본 6건이다.
 * 좌표는 대략적인 위치이고, 편의시설·개방시간은 실제 확인한 값이 아니다.
 *
 * 3단계(공공데이터 수집)와 4단계(지오코딩)가 끝나면 이 파일을 삭제하고
 * lib/toilets/fetch-toilets.ts 의 본문만 Supabase 쿼리로 바꾸면 된다.
 * 필드 구조는 toilets 테이블과 동일하므로 화면 코드는 손대지 않는다.
 */

const NOW = "2026-07-30T00:00:00.000Z";

export const MOCK_TOILETS: Toilet[] = [
  {
    id: "mock-0001",
    source: "public",
    external_id: null,
    name: "인하대학교 학생회관 화장실",
    road_address: "인천 미추홀구 인하로 100",
    jibun_address: null,
    lat: 37.4508,
    lng: 126.6541,
    geocode_status: "ok",
    unisex: false,
    male_toilet_count: 3,
    male_urinal_count: 5,
    female_toilet_count: 5,
    open_hours: "평일 07:00 ~ 22:00",
    has_diaper_table: false,
    has_disabled_toilet: true,
    manager: "인하대학교",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "mock-0002",
    source: "public",
    external_id: null,
    name: "인하대역 공중화장실",
    road_address: "인천 미추홀구 경인로 지하 1",
    jibun_address: null,
    lat: 37.4419,
    lng: 126.65,
    geocode_status: "ok",
    unisex: false,
    male_toilet_count: 2,
    male_urinal_count: 3,
    female_toilet_count: 4,
    open_hours: "05:30 ~ 24:00 (첫차~막차)",
    has_diaper_table: true,
    has_disabled_toilet: true,
    manager: "한국철도공사",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "mock-0003",
    source: "public",
    external_id: null,
    name: "용현시장 공영주차장 화장실",
    road_address: "인천 미추홀구 용현동 627",
    jibun_address: null,
    lat: 37.4456,
    lng: 126.6553,
    geocode_status: "ok",
    unisex: true,
    male_toilet_count: 1,
    male_urinal_count: 1,
    female_toilet_count: 1,
    open_hours: "09:00 ~ 20:00",
    has_diaper_table: false,
    has_disabled_toilet: false,
    manager: "미추홀구청",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "mock-0004",
    source: "public",
    external_id: null,
    name: "수봉공원 화장실",
    road_address: "인천 미추홀구 수봉로 8",
    jibun_address: null,
    lat: 37.459,
    lng: 126.647,
    geocode_status: "ok",
    unisex: false,
    male_toilet_count: 2,
    male_urinal_count: 4,
    female_toilet_count: 3,
    open_hours: "24시간",
    has_diaper_table: false,
    has_disabled_toilet: true,
    manager: "미추홀구청",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "mock-0005",
    source: "public",
    external_id: null,
    name: "인하대병원 본관 1층 화장실",
    road_address: "인천 미추홀구 인항로 27",
    jibun_address: null,
    lat: 37.4516,
    lng: 126.6626,
    geocode_status: "ok",
    unisex: false,
    male_toilet_count: 4,
    male_urinal_count: 6,
    female_toilet_count: 6,
    open_hours: "24시간",
    has_diaper_table: true,
    has_disabled_toilet: true,
    manager: "인하대병원",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: "mock-0006",
    source: "public",
    external_id: null,
    name: "용현5동 주민센터 화장실",
    road_address: "인천 미추홀구 인하로 141",
    jibun_address: null,
    lat: 37.447,
    lng: 126.652,
    geocode_status: "ok",
    unisex: true,
    male_toilet_count: 1,
    male_urinal_count: 2,
    female_toilet_count: 2,
    open_hours: "평일 09:00 ~ 18:00",
    has_diaper_table: false,
    has_disabled_toilet: false,
    manager: "용현5동 주민센터",
    phone: null,
    created_at: NOW,
    updated_at: NOW,
  },
];
